# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Version
mod_version=1.21.1-0.12.19
mod_release_type=alpha

## Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
java_version=21
# Latest NeoForm versions: https://projects.neoforged.net/neoforged/neoform
neoform_version=1.21.1-20240808.144430
# Latest Parchment versions: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# The Mixin and MixinExtras versions should match those used by NeoForge and Fabric
mixin_version=0.8.7
mixinextras_version=0.5.3

patchouli_version=1.21.1-93
forgeconfigapiport_version=21.1.6

## NeoForge
# Latest NeoForge versions: https://projects.neoforged.net/neoforged/neoforge
neo_version=21.1.233
neo_version_range=[21.1.233,)
neo_loader_version_range=[4,)

kubejs_version=2101.7.2-build.233

## Mod Metadata
mod_id=totemic
mod_name=Totemic
mod_license=MIT
mod_credits=nojustgavin, Nefilto, ZestyBlaze, VincentLongiug, WayofTime, Joshie, Poppycocks, Dylan4Ever, Vazkii, Kerri Lake
mod_authors=Pokefenn, ljfa, Sunconure11
mod_description=A magic mod about Totem Poles, nature and the power of music.
mod_group_id=pokefenn.totemic
