# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Version
version=26.1.2-0.12.19
release_type=alpha

## Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
java_version=25
# Latest NeoForm versions: https://projects.neoforged.net/neoforged/neoform
neoform_version=26.1.2-1
# Latest Parchment versions: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
# The Mixin and MixinExtras versions should match those used by NeoForge and Fabric
mixin_version=0.8.7
mixinextras_version=0.5.4

patchouli_version=26.1-94
forgeconfigapiport_version=26.1.5

## NeoForge
# Latest NeoForge versions: https://projects.neoforged.net/neoforged/neoforge
neo_version=26.1.2.109
neo_version_range=[26.1.2.109,)

kubejs_version=26.1.2-8.0.6

## Mod Metadata
mod_id=totemic
mod_name=Totemic
mod_license=MIT
mod_credits=nojustgavin, Nefilto, ZestyBlaze, VincentLongiug, WayofTime, Joshie, Poppycocks, Dylan4Ever, Vazkii, Kerri Lake
mod_authors=Pokefenn, ljfa, Sunconure11
mod_description=A magic mod about Totem Poles, nature and the power of music.
group=pokefenn.totemic
