#!/bin/bash
# Creates a new Github release with the current version and changelog
PRERELEASE=false
BRANCH=$(git symbolic-ref --short HEAD)
VERSION=$(sed -nr 's/mod_version=(.*)/\1/p' gradle.properties)
if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
    echo "Version number could not be determined" >&2
    exit 1
fi
if git tag | grep -q "$VERSION" -; then
    echo "Tag '$VERSION' already exists" >&2
    exit 1
fi

echo "Publishing Github release '$VERSION' on branch '$BRANCH'"

export PRERELEASE BRANCH VERSION
curl -L \
  --variable '%BRANCH' --variable '%VERSION' --variable '%PRERELEASE' \
  --variable '%GH_TOKEN@../totemic_gh_token' \
  --variable '%CHANGELOG@changelog.md' \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  --expand-header "Authorization: Bearer {{GH_TOKEN:trim}}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/TeamTotemic/Totemic/releases \
  --expand-data '{"tag_name":"{{VERSION:json}}","target_commitish":"{{BRANCH:json}}","name":"{{VERSION:json}}","body":"{{CHANGELOG:json}}","draft":false,"prerelease":{{PRERELEASE}},"generate_release_notes":false}'

git fetch --tags
