#!/bin/bash
# Creates a new Github release with the current version and changelog
PRERELEASE=true
LATEST=false
TARGET_BRANCH=1.7.10

BRANCH=$(git symbolic-ref --short HEAD)
if [ $? -ne 0 ] || [ "$BRANCH" != "$TARGET_BRANCH" ]; then
    echo "Incorrect branch, should be $TARGET_BRANCH" >&2
    exit 1
fi

#VERSION=$(sed -nr 's/mod_version=(.*)/\1/p' gradle.properties)
VERSION=$(sed -nr 's/version = "(.*)"/\1/p' build.gradle.kts)
if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
    echo "Version number could not be determined" >&2
    exit 1
fi
if git tag | grep -q "$VERSION"; then
    echo "Tag '$VERSION' already exists" >&2
    exit 1
fi

# Check for uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
    echo "There are uncommitted changes in the working directory:" >&2
    git status --short >&2
    exit 1
fi

# Check for unpushed commits
git fetch
if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{upstream})" ]; then
    echo "There are unpushed or unpulled changes in the repository:" >&2
    echo >&2
    git status >&2
    exit 1
fi

echo "Publishing Github release '$VERSION' on branch '$BRANCH'"

export PRERELEASE BRANCH VERSION LATEST
curl -L \
  --variable '%PRERELEASE' --variable '%BRANCH' --variable '%VERSION' --variable '%LATEST' \
  --variable '%GH_TOKEN@../totemic_gh_token' \
  --variable '%CHANGELOG@changelog.md' \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  --expand-header "Authorization: Bearer {{GH_TOKEN:trim}}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/TeamTotemic/Totemic/releases \
  --expand-data '{"tag_name":"{{VERSION:json}}","target_commitish":"{{BRANCH:json}}","name":"{{VERSION:json}}","body":"{{CHANGELOG:json}}","draft":false,"prerelease":{{PRERELEASE}},"generate_release_notes":false,"make_latest":"{{LATEST}}"}'

git fetch --tags
