modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TeamTotemic/Totemic/issues"

[[mods]]
modId="totemic"
version="${file.jarVersion}"
displayName="Totemic"
updateJSONURL="https://raw.githubusercontent.com/TeamTotemic/Totemic/version/version.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/totemic"
logoFile="totemic_logo.png"
credits="nojustgavin, Nefilto, ZestyBlaze, VincentLongiug, WayofTime, Joshie, Poppycocks, Dylan4Ever, Vazkii, Kerri Lake"
authors="${mod_authors}"
description='''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
    config="totemic.mixins.json"

[[dependencies.totemic]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.totemic]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.totemic]]
    modId="patchouli"
    type="optional"
    versionRange="[1.21-87,)"
    ordering="NONE"
    side="BOTH"
