plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

repositories {
    mavenLocal()
    // Patchouli
    maven {
        url = 'https://maven.blamejared.com'
        content {
            includeGroup 'vazkii.patchouli'
        }
    }
    // Forge Config API Port
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

base {
    archivesName = 'Totemic-common'
}

neoForge {
    neoFormVersion = project.neoform_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
        validateAccessTransformers = true
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:${project.mixin_version}"
    compileOnly "io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"

    compileOnly "vazkii.patchouli:Patchouli-xplat:${project.patchouli_version}"
    compileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${project.forgeconfigapiport_version}"
}
