plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

version = mod_version
group = mod_group_id

repositories {
    // Patchouli
    maven {
        url = 'https://maven.blamejared.com'
        content {
            includeGroup 'vazkii.patchouli'
        }
    }
    // KubeJS
    maven {
        url = 'https://maven.latvian.dev/releases'
        content {
            includeGroup 'dev.latvian.mods'
            includeGroup 'dev.latvian.apps'
        }
    }
    maven {
        url = 'https://jitpack.io'
        content {
            includeGroup 'com.github.rtyley'
        }
    }
}

base {
    archivesName = 'Totemic-neoforge'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
        validateAccessTransformers = true
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            //programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('run-gameTestServer')
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        commonData {
            data()
            //gameDirectory = project.file('run-data')
            programArguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', project.project(':common').file('src/generated/resources/').getAbsolutePath(),
                '--existing', project.project(":common").file('src/main/resources/').getAbsolutePath())
            systemProperty 'totemic.commonDatagen', 'true'
        }

        neoForgeData {
            data()
            //gameDirectory = project.file('run-data')
            programArguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath(),
                '--existing', project.project(":common").file('src/main/resources/').getAbsolutePath())
            systemProperty 'totemic.neoForgeDatagen', 'true'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    
    addModdingDependenciesTo sourceSets.test

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project(":common").sourceSets.main)
            sourceSet(sourceSets.test)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation project(":common")

    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE:api"
    runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE"

    api("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(project(":common").sourceSets.main.allSource)
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    dependsOn(project(":common").sourceSets.main.resources)
    from(project(":common").sourceSets.main.resources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(project(":common").sourceSets.main.allJava)
    source(project(":common").sourceSets.main.allJava)
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            loader_version_range   : neo_loader_version_range,
            patchouli_version      : patchouli_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_credits            : mod_credits,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

task apiSrcJar(type: Jar) {
    from(sourceSets.main.java) {
        include 'pokefenn/totemic/api/**'
    }
    archiveAppendix = 'api'
    archiveClassifier = 'sources'
}

tasks.named('assemble') {
    dependsOn apiSrcJar
}

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('curseForgeApiKey')
    
    def mainFile = upload(237541, jar)
    mainFile.addModLoader('NeoForge')
    mainFile.releaseType = mod_release_type
    mainFile.changelog = file('../changelog.md')
    mainFile.changelogType = 'markdown'
    mainFile.addOptional('patchouli')
    
    def apiSrcFile = mainFile.withAdditionalFile(apiSrcJar)
}

modrinth {
    token = findProperty('modrinthApiToken')
    projectId = 'fenns_totemic'
    versionType = mod_release_type
    uploadFile = jar
    gameVersions = [minecraft_version]
    loaders = ['neoforge']
    changelog = file('../changelog.md').text
    dependencies {
        optional.project 'patchouli'
    }
    additionalFiles = [apiSrcJar]
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    // Fix Gradle build failing due to no excutable tests being discovered
    failOnNoDiscoveredTests = false
}

test.dependsOn runGameTestServer
