plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

repositories {
    // Patchouli
    maven {
        url = 'https://maven.blamejared.com'
        content {
            includeGroup 'vazkii.patchouli'
        }
    }
    // KubeJS
    maven {
        url = 'https://maven.latvian.dev/releases'
        content {
            includeGroup 'dev.latvian.mods'
            includeGroup 'dev.latvian.apps'
        }
    }
    maven {
        url = 'https://jitpack.io'
        content {
            includeGroup 'com.github.rtyley'
        }
    }
}

base {
    archivesName = 'Totemic-neoforge'
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
        validateAccessTransformers = true
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            //programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = 'gameTestServer'
            gameDirectory = project.file('run-gameTestServer')
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        commonData {
            data()
            programArguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', project.project(':common').file('src/generated/resources/').getAbsolutePath(),
                '--existing', project.project(':common').file('src/main/resources/').getAbsolutePath())
            systemProperty 'totemic.commonDatagen', 'true'
        }

        neoForgeData {
            data()
            programArguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath(),
                '--existing', project.project(':common').file('src/main/resources/').getAbsolutePath())
            systemProperty 'totemic.neoForgeDatagen', 'true'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    
    addModdingDependenciesTo sourceSets.test

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project(':common').sourceSets.main)
            sourceSet(sourceSets.test)
        }
    }
}

dependencies {
    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE:api"
    runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE"

    api("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            loader_version_range   : neo_loader_version_range,
            patchouli_version      : patchouli_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_credits            : mod_credits,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_license            : mod_license,
            mod_version            : version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('curseForgeApiKey')
    
    def mainFile = upload(237541, jar)
    mainFile.addModLoader('NeoForge')
    mainFile.releaseType = release_type
    mainFile.changelog = file('../changelog.md')
    mainFile.changelogType = 'markdown'
    mainFile.addOptional('patchouli')
    
    mainFile.withAdditionalFile(apiJar)
}

modrinth {
    token = findProperty('modrinthApiToken')
    projectId = 'fenns_totemic'
    versionType = release_type
    uploadFile = jar
    gameVersions = [minecraft_version]
    loaders = ['neoforge']
    changelog = file('../changelog.md').text
    dependencies {
        optional.project 'patchouli'
    }
    additionalFiles = [apiJar]
}

test {
    // Fix Gradle build failing since we have no unit tests in src/test
    failOnNoDiscoveredTests = false
}
